version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my_php_app
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: my_mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: my_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
